// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MedSysProject.Models;

public partial class BlogCategory
{
    public int BlogClassId { get; set; }

    public string BlogCategory1 { get; set; }

    public virtual ICollection<Blog> Blogs { get; set; } = new List<Blog>();
}