// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MedSysProject.Models;

public partial class Blog
{
    public int BlogId { get; set; }

    public string Title { get; set; }

    public int ArticleClassId { get; set; }

    public int Views { get; set; }

    public DateTime CreatedAt { get; set; }

    public string Content { get; set; }

    public byte[] BlogImage { get; set; }

    public int EmployeeId { get; set; }

    public virtual BlogCategory ArticleClass { get; set; }

    public virtual ICollection<Comment> Comments { get; set; } = new List<Comment>();

    public virtual Employee Employee { get; set; }
}