// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MedSysProject.Models;

public partial class BlogManagement
{
    public int BlogPermissionId { get; set; }

    public string PermissionType { get; set; }

    public virtual ICollection<EmployeeClass> EmployeeClasses { get; set; } = new List<EmployeeClass>();
}