// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MedSysProject.Models;

public partial class Message
{
    public int MessageId { get; set; }

    public int? RoomId { get; set; }

    public int? MemberId { get; set; }

    public int? EmployeeId { get; set; }

    public string MessageContent { get; set; }

    public bool? ReadState { get; set; }

    public string SendTime { get; set; }

    public virtual Employee Employee { get; set; }

    public virtual Member Member { get; set; }

    public virtual Room Room { get; set; }
}