// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace MedSysProject.Models;

public partial class Order
{
    public int OrderId { get; set; }

    public DateTime OrderDate { get; set; }

    public int? MemberId { get; set; }

    public int? ShipId { get; set; }

    public int? PayId { get; set; }

    public int? StateId { get; set; }

    public DateTime? ShipDate { get; set; }

    public DateTime? DeliveryDate { get; set; }

    public string MerchantTradeNo { get; set; }

    public string TradeNo { get; set; }
    [JsonIgnore]
    public virtual Member Member { get; set; }
    [JsonIgnore]
    public virtual ICollection<OrderDetail> OrderDetails { get; set; } = new List<OrderDetail>();
    [JsonIgnore]
    public virtual OrderPay Pay { get; set; }
    [JsonIgnore]
    public virtual ICollection<ReturnProduct> ReturnProducts { get; set; } = new List<ReturnProduct>();
    [JsonIgnore]
    public virtual OrderShip Ship { get; set; }
    [JsonIgnore]
    public virtual OrderState State { get; set; }
}