// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace MedSysProject.Models;

public partial class OrderState
{
    public int StateId { get; set; }

    public string StateName { get; set; }

    public string StateDetailed { get; set; }

    public int? OrderStatus { get; set; }
    [JsonIgnore]
    public virtual ICollection<Order> Orders { get; set; } = new List<Order>();
}