// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace MedSysProject.Models;

public partial class ProductsCategory
{
    public int CategoriesId { get; set; }

    public string CategoriesName { get; set; }
    [JsonIgnore]
    public virtual ICollection<ProductsClassification> ProductsClassifications { get; set; } = new List<ProductsClassification>();
}