// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace MedSysProject.Models;

public partial class ProductReview
{
    public int ProductReviewId { get; set; }

    public int? MemberId { get; set; }

    public int? ProductId { get; set; }

    public string ReviewContent { get; set; }

    public DateTime? Timestamp { get; set; }

    public bool? IsLike { get; set; }
    [JsonIgnore]
    public virtual Member Member { get; set; }
    [JsonIgnore]
    public virtual Product Product { get; set; }
}