// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MedSysProject.Models;

public partial class Product
{
    public int ProductId { get; set; }

    public string ProductName { get; set; }

    public decimal? UnitPrice { get; set; }

    public string License { get; set; }

    public string Ingredient { get; set; }

    public string Description { get; set; }

    public int? UnitsInStock { get; set; }

    public bool? Discontinued { get; set; }

    public string FimagePath { get; set; }

    public int? Likecount { get; set; }

    public virtual ICollection<OrderDetail> OrderDetails { get; set; } = new List<OrderDetail>();

    public virtual ICollection<ProductsClassification> ProductsClassifications { get; set; } = new List<ProductsClassification>();

    public virtual ICollection<TrackingList> TrackingLists { get; set; } = new List<TrackingList>();
}