// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MedSysProject.Models;

public partial class ReportDetail
{
    public int ReportDetailId { get; set; }

    public int? ReportId { get; set; }

    public int? ItemId { get; set; }

    public string Result { get; set; }

    public virtual Item Item { get; set; }

    public virtual HealthReport Report { get; set; }
}